version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - sql_volume:/var/opt/mssql

  api:
    # ملاحظة: لو هترفع الملف ده للسيرفر عشان تسحب بيه، يفضل تستخدم السطر بتاع image وتمسح الـ build
    # لأن السيرفر معليهوش الكود المصدري عشان يبني منه.
    image: hadras/schoolproject-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # تأكد أن ملف الـ Dockerfile يحتوي على EXPOSE 8080
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # --- إعدادات قواعد البيانات (EF Core + Serilog) ---
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - Serilog__WriteTo__1__Args__connectionString=${DB_CONNECTION}

      # --- إعدادات JWT السرية ---
      - JwtSettings__Key=${JWT_KEY}

      # --- إعدادات الإيميل السرية ---
      - EmailSettings__Password=${EMAIL_PASS}

volumes:
  sql_volume:
